name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          path: 'repo'
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./repo/docs/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: ./repo/docs

      - name: Build website
        run: npm run build
        working-directory: ./repo/docs

      - name: Copy CNAME to build directory
        run: echo "dev.ingonyama.com" > ./build/CNAME
        working-directory: ./repo/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo/docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          working-directory: ./repo/docs
